// webapp/src/components/Home.vue
<template>
  <div class="home">
    <md-card>
      <md-card-header>
        <div class="md-title">QSO Statistics</div>
      </md-card-header>

      <md-card-content>
        <md-progress v-if="!qso" md-indeterminate></md-progress>
        <div v-if="qso">
          <div class="stats-box">
            <div class="stats-title">Total</div>
            <div class="stats-value">{{qso[0]}}</div>
          </div>
          <div class="stats-box">
            <div class="stats-title">This Year</div>
            <div class="stats-value">{{qso[1]}}</div>
          </div>
          <div class="stats-box">
            <div class="stats-title">This Month</div>
            <div class="stats-value">{{qso[2]}}</div>
          </div>
        </div>
      </md-card-content>
    </md-card>

    <md-card>
      <md-card-header>
        <div class="md-title">DXCC Statistics</div>
      </md-card-header>

      <md-card-content>
        <md-progress v-if="!dxcc" md-indeterminate></md-progress>
        <div v-if="dxcc">
          <div class="stats-box">
            <div class="stats-title">Worked</div>
            <div class="stats-value">{{dxcc.worked}}</div>
          </div>
          <div class="stats-box">
            <div class="stats-title">Confirmed</div>
            <div class="stats-value">{{dxcc.confirmed}}</div>
          </div>
          <div class="stats-box">
            <div class="stats-title">LoTW</div>
            <div class="stats-value">{{dxcc.lotw}}</div>
          </div>
          <div class="stats-box">
            <div class="stats-title">Card</div>
            <div class="stats-value">{{dxcc.card}}</div>
          </div>
        </div>
      </md-card-content>
    </md-card>

    <md-card>
      <md-card-header>
        <div class="md-title">Top Modes</div>
      </md-card-header>

      <md-card-content>
        <md-progress v-if="!modes" md-indeterminate></md-progress>
        <md-table v-if="modes">
          <md-table-body>
            <md-table-row v-for="mode in modes" :key="mode.key[0]">
              <md-table-cell><b>{{mode.key[0]}}</b></md-table-cell>
              <md-table-cell md-numeric>{{mode.value}}</md-table-cell>
            </md-table-row>
          </md-table-body>
        </md-table>
      </md-card-content>
    </md-card>
  </div>
</template>

<script>
export default {
  name: 'home',
  data () {
   return {
      qso: null,
      dxcc: null,
      modes: null
    }
  },
  created () {
    var date = new Date()
    var year = date.getUTCFullYear().toString()
    var month = date.getUTCMonth() + 1
    var month_str = month < 10 ?  "0" + month.toString() : month.toString()

    // Total QSO Count
    var total = this.$http.get("contacts/_stats", {
      params: {group_level: 0}
    })

    // Yearly QSO Count
    var yearly = this.$http.get("contacts/_stats", {
      params: {
        group_level: 1,
        startkey: JSON.stringify([year]),
        endkey: JSON.stringify([year, {}])
      }
    })

    // Monthly QSO Count
    var monthly = this.$http.get("contacts/_stats", {
      params: {
        group_level: 2,
        startkey: JSON.stringify([year, month_str]),
        endkey: JSON.stringify([year, month_str, {}])
      }
    })

    Promise.all([total, yearly, monthly]).then((results) => {
      let qso = [];

      results.forEach(function(response) {
        let rows = response.body.rows
        let value = rows.length ? rows[0].value : 0
        qso.push(value);
      });

      this.qso = qso;
    })

    // DXCC Count
    this.$http.get("contacts/_dxcc_count").then(response => {
      this.dxcc = response.body
    })

    // Modes
    this.$http.get("contacts/_view/byMode", {
      params: {
        group_level: 1,
        include_docs: false,
        descending: false
      }
    }).then(response => {
      let modes = response.body.rows
      modes.sort(function(a, b) {
        if (a.value > b.value) return -1;
        if (b.value > a.value) return 1;
        return 0;
      })
      this.modes = modes.slice(0, 5)
    })
  }
}
</script>

<style scoped>
.md-card {
  max-width: 320px;
  margin: 0 4px 16px;
  display: inline-block;
  vertical-align: top;
}
.stats-box {
  display: inline-block;
  margin-right: 1em;
}
.stats-title {
  opacity: .54;
  padding-bottom: 5px;
  text-align: center;
  font-size: 14px;
}
.stats-value {
  text-align: center;
  font-size: 1.8em;
}
</style>

// webapp/app/+home/home.component.ts
import { Component } from "@angular/core";
import { ContactService } from "../shared/index";

@Component({
    templateUrl: "./home.component.html"
})
export class HomeComponent {
    qso_stats = {total: 0, year: 0, month: 0};
    dxcc_count = {worked: 0, confirmed: 0, card: 0, lotw:0};
    modes: Array<[string, number]> = [];

    constructor(public api: ContactService) {
        this.reload();
    }

    reload() {
        var date = new Date();
        var year = date.getUTCFullYear().toString();
        var month = date.getUTCMonth() + 1;
        var month_str = month < 10 ?  "0" + month.toString() : month.toString();

        // Query total QSOs
        this.api.stats({group_level: 0}).subscribe(result => {
            this.qso_stats.total = result.rows.length ? result.rows[0].value : 0
        });

        // Query QSOs for this year
        var year_options = {
            group_level: 1,
            startkey: JSON.stringify([year]),
            endkey: JSON.stringify([year, {}])
        };

        this.api.stats(year_options).subscribe(result => {
            this.qso_stats.year = result.rows.length ? result.rows[0].value : 0;
        });

        // Query QSOs for this month
        var month_options = {
           group_level: 2,
           startkey: JSON.stringify([year, month_str]),
           endkey: JSON.stringify([year, month_str, {}])
        };

        this.api.stats(month_options).subscribe(result => {
            this.qso_stats.month = result.rows.length ? result.rows[0].value : 0;
        });

        // Query DXCC count
        this.api.dxccCount().subscribe(result => {
            this.dxcc_count = result;
        });

        // Query modes
        var mode_options = {
            group_level: 1,
            include_docs: false,
            descending: false
        };

        this.api.byMode(mode_options).subscribe(modes => {
            this.modes = [];
            for (var i in modes.rows) {
                var name = modes.rows[i].key[0];
                var count = modes.rows[i].value;
                this.modes.push([name, count]);
            }
        });
    }
}

<h1>Welcome to CloudShack!</h1>

<div class="dashboard">
  <div class="box statistics">
    <div class="box-title">
      <i class="fa fa-bar-chart"></i>
      QSO Statistics
    </div>
    <div class="box-content">
      <div class="column">
        <small>Total</small>
        <div class="value">{{qso_stats.total}}</div>
      </div>
      <div class="column">
        <small>This Year</small>
        <div class="value">{{qso_stats.year}}</div>
      </div>
      <div class="column">
        <small>This Month</small>
        <div class="value">{{qso_stats.month}}</div>
      </div>
      <div style="clear: both;"></div>
    </div>
  </div>

  <div class="box statistics">
    <div class="box-title">
      <i class="fa fa-globe"></i>
      DXCC Statistics
    </div>
    <div class="box-content">
      <div class="column">
        <small>Worked</small>
        <div class="value">{{dxcc_count.worked}}</div>
      </div>
      <div class="column">
        <small>Confirmed</small>
        <div class="value">{{dxcc_count.confirmed}}</div>
      </div>
      <div class="column">
        <small>LoTW</small>
        <div class="value">{{dxcc_count.lotw}}</div>
      </div>
      <div class="column">
        <small>Card</small>
        <div class="value">{{dxcc_count.card}}</div>
      </div>
      <div style="clear: both;"></div>
    </div>
  </div>

  <div class="box statistics">
    <div class="box-title">
      <i class="fa fa-pie-chart"></i>
      Mode Statistics
    </div>
    <table class="box-table">
      <tr *ngFor="let mode of modes">
        <td>{{mode[0]}}</td>
        <td>{{mode[1]}}</td>
      </tr>
    </table>
  </div>
</div>

<p>
  <i class="fa fa-hand-o-right"></i>
  <a *ngIf="qso_stats.total == 0" href="/#/contact/new">
    Log your first contact!
  </a>
  <a *ngIf="qso_stats.total > 0" href="/#/contact/new">
    Log a new contact
  </a>
</p>
