// webapp/app/+settings/settings.component.ts
import { Component } from "@angular/core";
import { Http, Response } from "@angular/http";

@Component({
    templateUrl: "./settings.component.html"
})
export class SettingsComponent {
    config = {
        cluster: {},
        hamqth: {},
        database: {},
        sync: {},
        wsjt: {}
    };

    constructor(public http: Http) {
        this.http.get("/config")
            .map((res: Response) => res.json())
            .subscribe(result => {
                Object.assign(this.config, result);
                console.log(result);
            }, error => {
                console.log("Failed to fetch config.");
            });
    }

    save() {
        this.http.post("/config", JSON.stringify(this.config))
            .subscribe(result => {
                console.log("Config saved.")
            }, error => {
                console.log("Failed to save contact.");
            })
    }
}

<h1>Settings</h1>

<tabs>
  <tab title="Callbook" active="true">
    <h4>HamQTH</h4>
    <div class="form-group">
      <label for="hamqth-username">Username</label>
      <input type="text" id="hamqth-username" [(ngModel)]="config.hamqth.user" />
    </div>
    <div class="form-group">
      <label for="hamqth-password">Password</label>
      <input type="password" id="hamqth-password" [(ngModel)]="config.hamqth.password" />
    </div>
  </tab>

  <tab title="DX Cluster">
    <div class="form-group">
      <label for="cluster-host">Host</label>
      <input type="text" id="cluster-host" [(ngModel)]="config.cluster.host" />
    </div>
    <div class="form-group">
      <label for="cluster-port">Port</label>
      <input type="number" step="1" min="1" max="65535" id="cluster-port"
        [(ngModel)]="config.cluster.port" />
    </div>
    <div class="form-group">
      <label for="cluster-user">User</label>
      <input type="text" id="cluster-user" [(ngModel)]="config.cluster.user" />
    </div>
  </tab>

  <tab title="Database">
    <div>
      <div class="form-group">
        <label for="db-host">Host</label>
        <input type="text" id="db-host" [(ngModel)]="config.database.host" />
      </div>
      <div class="form-group">
        <label for="db-port">Port</label>
        <input type="number" step="1" min="1" max="65535" id="db-port"
          [(ngModel)]="config.database.port" />
      </div>
      <div class="form-group">
        <label for="db-protocol">Protocol</label>
        <input type="text" id="db-protocol" [(ngModel)]="config.database.protocol" />
      </div>
    </div>
    <div>
      <div class="form-group">
        <label for="db-name">Name</label>
        <input type="text" id="db-name" [(ngModel)]="config.database.name" />
      </div>
      <div class="form-group">
        <label for="db-user">User</label>
        <input type="text" id="db-user" [(ngModel)]="config.database.user" />
      </div>
      <div class="form-group">
        <label for="db-password">Password</label>
        <input type="password" id="db-password" [(ngModel)]="config.database.password" />
      </div>
    </div>
  </tab>
  <tab title="Sync">
    <div class="form-group">
      <label for="sync-user">User</label>
      <input type="text" id="sync-user" [(ngModel)]="config.sync.user" />
    </div>
    <div class="form-group">
      <label for="sync-password">Password</label>
      <input type="password" id="sync-password" [(ngModel)]="config.sync.password" />
    </div>
    <div class="form-group">
      <label for="sync-key">Access Key</label>
      <input type="text" id="sync-key" [(ngModel)]="config.sync.key" />
    </div>
  </tab>
  <tab title="WSJT">
    <div>
      <div class="form-group">
        <label for="wsjt-port">Port</label>
        <input type="number" step="1" min="1" max="65535"  id="wsjt-port" [(ngModel)]="config.wsjt.port" />
      </div>
    </div>
    <div>
      <div class="form-group">
        <label for="wsjt-forward-host">Forward Host</label>
        <input type="text" id="wsjt-forward-host" [(ngModel)]="config.wsjt.forward_host" />
      </div>
      <div class="form-group">
        <label for="wsjt-forward-port">Forward Port</label>
        <input type="number" step="1" min="1" max="65535"  id="wsjt-forward-port" [(ngModel)]="config.wsjt.forward_port" />
      </div>
    </div>
  </tab>
</tabs>

<div class="box-transparent">
  <div class="box-content">
    <button (click)="save()" class="btn-primary">
      <i class="fa fa-check"></i> Save
    </button>
  </div>
</div>

// webapp/src/components/Settings.vue
<template>
  <v-container>
    <v-card>
      <v-tabs dark fixed centered>
        <v-tabs-bar>
          <v-tabs-slider></v-tabs-slider>
          <v-tabs-item href="#callbook">Callbook</v-tabs-item>
          <v-tabs-item href="#cluster">DX Cluster</v-tabs-item>
          <v-tabs-item href="#database">Database</v-tabs-item>
          <v-tabs-item href="#sync">Sync</v-tabs-item>
          <v-tabs-item href="#wsjt">WSJT</v-tabs-item>
        </v-tabs-bar>
        <v-tabs-items>
          <v-tabs-content id="callbook">
            <v-container grid-list-lg>
              <b>HamQTH</b>
              <v-layout row>
                <v-flex sm6>
                  <v-text-field
                    label="Username"
                    v-model="config.hamqth.user">
                  </v-text-field>
                </v-flex>
                <v-flex sm6>
                  <v-text-field
                    label="Password"
                    type="password"
                    v-model="config.hamqth.user">
                  </v-text-field>
                </v-flex>
              </v-layout>
            </v-container>
          </v-tabs-content>
          <v-tabs-content id="cluster">
            <v-container grid-list-lg>
              <v-layout row>
                <v-flex sm4>
                  <v-text-field
                    label="Host"
                    v-model="config.cluster.host">
                  </v-text-field>
                </v-flex>
                <v-flex sm4>
                  <v-text-field
                    label="Port"
                    type="number" step="1" min="1" max="65535"
                    v-model.number="config.cluster.port">
                  </v-text-field>
                </v-flex>
                <v-flex sm4>
                  <v-text-field
                    label="User"
                    v-model="config.cluster.user">
                  </v-text-field>
                </v-flex>
              </v-layout>
            </v-container>
          </v-tabs-content>
          <v-tabs-content id="database">
            <v-container grid-list-lg>
              <v-layout row>
                <v-flex sm4>
                  <v-text-field
                    label="Host"
                    v-model="config.database.host">
                  </v-text-field>
                </v-flex>
                <v-flex sm4>
                  <v-text-field
                    label="Port"
                    type="number" step="1" min="1" max="65535"
                    v-model.number="config.database.port">
                  </v-text-field>
                </v-flex>
                <v-flex sm4>
                  <v-text-field
                    label="Protocol"
                    v-model="config.database.protocol">
                  </v-text-field>
                </v-flex>
              </v-layout>
              <v-layout row>
                <v-flex sm4>
                  <v-text-field
                    label="Name"
                    v-model="config.database.name">
                  </v-text-field>
                </v-flex>
                <v-flex sm4>
                  <v-text-field
                    label="User"
                    v-model="config.database.user">
                  </v-text-field>
                </v-flex>
                <v-flex sm4>
                  <v-text-field
                    label="Password"
                    type="password"
                    v-model="config.database.password">
                  </v-text-field>
                </v-flex>
              </v-layout>
            </v-container>
          </v-tabs-content>
          <v-tabs-content id="sync">
            <v-container grid-list-lg>
              <v-layout row>
                <v-flex sm4>
                  <v-text-field
                    label="User"
                    v-model="config.sync.user">
                  </v-text-field>
                </v-flex>
                <v-flex sm4>
                  <v-text-field
                    label="Password"
                    type="password"
                    v-model="config.sync.password">
                  </v-text-field>
                </v-flex>
                <v-flex sm4>
                  <v-text-field
                    label="Access Key"
                    v-model="config.sync.key">
                  </v-text-field>
                </v-flex>
              </v-layout>
            </v-container>
          </v-tabs-content>
          <v-tabs-content id="wsjt">
            <v-container grid-list-lg>
              <v-layout row>
                <v-flex sm1>
                  <v-text-field
                    label="Port"
                    type="number" step="1" min="1" max="65535"
                    v-model.number="config.wsjt.port">
                  </v-text-field>
                </v-flex>
              </v-layout>
            </v-container>
          </v-tabs-content>
        </v-tabs-items>
      </v-tabs>
    </v-card>

    <br>
    <div>
      <v-btn primary
             :loading="saving"
             :disabled="saving"
             @click="save()">
        {{$t("save")}}
      </v-btn>

      <v-btn error @click="reset()">
        {{$t("reset")}}
      </v-btn>
    </div>
  </v-container>
</template>

<script>
export default {
  data: function() {
    return {
      config: {
        hamqth: {},
        cluster: {},
        database: {},
        sync: {},
        wsjt: {}
      },
      saving: false
    }
  },
  created: function() {
    this.$http.get("config").then((response) => {
      Object.assign(this.config, response.data)
    })
  },
  methods: {
    save: function() {
      this.saving = true
        this.$http.post("config", JSON.stringify(this.config)).then((response) => {
          this.saving = false
          this.$flash.success("Settings updated.")
      })
    }
  }
}
</script>
